{Pascal wrappper for proj library Supports only from the version 6 API.}
{This License applies only to this wrapper and not the proj itself}
{For the latest proj visit https://proj.org/   }
{* Author: Domingo Galmes <dgalmesp@gmail.com>  29-11-2020
******************************************************************************
* Copyright (c) 2020,2021 Domingo Galmés
*
* Permission is hereby granted, free of charge, to any person obtaining a
* copy of this software and associated documentation files (the "Software"),
* to deal in the Software without restriction, including without limitation
* the rights to use, copy, modify, merge, publish, distribute, sublicense,
* and/or sell copies of the Software, and to permit persons to whom the
* Software is furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO COORD SHALL
* THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
* FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*****************************************************************************}
{ original proj_constants.h license }
{*****************************************************************************
 *
 * Project:  PROJ
 * Purpose:  Constants
 * Author:   Even Rouault <even dot rouault at spatialys dot com>
 *
 ******************************************************************************
 * Copyright (c) 2018, Even Rouault <even dot rouault at spatialys dot com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the 'Software'),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ***************************************************************************}
unit proj_constants;

interface

const
{ Projection methods }

EPSG_NAME_METHOD_TRANSVERSE_MERCATOR='Transverse Mercator';
EPSG_CODE_METHOD_TRANSVERSE_MERCATOR=9807;

EPSG_NAME_METHOD_TRANSVERSE_MERCATOR_SOUTH_ORIENTATED='Transverse Mercator (South Orientated)';
EPSG_CODE_METHOD_TRANSVERSE_MERCATOR_SOUTH_ORIENTATED=9808;

PROJ_WKT2_NAME_METHOD_TWO_POINT_EQUIDISTANT='Two Point Equidistant';

EPSG_NAME_METHOD_LAMBERT_CONIC_CONFORMAL_1SP='Lambert Conic Conformal (1SP)';
EPSG_CODE_METHOD_LAMBERT_CONIC_CONFORMAL_1SP=9801;

EPSG_NAME_METHOD_NZMG='New Zealand Map Grid';
EPSG_CODE_METHOD_NZMG=9811;

EPSG_NAME_METHOD_TUNISIA_MAPPING_GRID='Tunisia Mapping Grid';
EPSG_CODE_METHOD_TUNISIA_MAPPING_GRID=9816;

EPSG_NAME_METHOD_ALBERS_EQUAL_AREA='Albers Equal Area';
EPSG_CODE_METHOD_ALBERS_EQUAL_AREA=9822;

EPSG_NAME_METHOD_LAMBERT_CONIC_CONFORMAL_2SP='Lambert Conic Conformal (2SP)';
EPSG_CODE_METHOD_LAMBERT_CONIC_CONFORMAL_2SP=9802;

EPSG_NAME_METHOD_LAMBERT_CONIC_CONFORMAL_2SP_BELGIUM='Lambert Conic Conformal (2SP Belgium)';
EPSG_CODE_METHOD_LAMBERT_CONIC_CONFORMAL_2SP_BELGIUM=9803;

EPSG_NAME_METHOD_LAMBERT_CONIC_CONFORMAL_2SP_MICHIGAN='Lambert Conic Conformal (2SP Michigan)';
EPSG_CODE_METHOD_LAMBERT_CONIC_CONFORMAL_2SP_MICHIGAN=1051;

EPSG_NAME_METHOD_MODIFIED_AZIMUTHAL_EQUIDISTANT='Modified Azimuthal Equidistant';
EPSG_CODE_METHOD_MODIFIED_AZIMUTHAL_EQUIDISTANT=9832;

EPSG_NAME_METHOD_GUAM_PROJECTION='Guam Projection';
EPSG_CODE_METHOD_GUAM_PROJECTION=9831;

EPSG_NAME_METHOD_BONNE='Bonne';
EPSG_CODE_METHOD_BONNE=9827;

PROJ_WKT2_NAME_METHOD_COMPACT_MILLER='Compact Miller';

EPSG_NAME_METHOD_LAMBERT_CYLINDRICAL_EQUAL_AREA_SPHERICAL='Lambert Cylindrical Equal Area (Spherical)';
EPSG_CODE_METHOD_LAMBERT_CYLINDRICAL_EQUAL_AREA_SPHERICAL=9834;

EPSG_NAME_METHOD_LAMBERT_CYLINDRICAL_EQUAL_AREA='Lambert Cylindrical Equal Area';
EPSG_CODE_METHOD_LAMBERT_CYLINDRICAL_EQUAL_AREA=9835;

EPSG_NAME_METHOD_CASSINI_SOLDNER='Cassini-Soldner';
EPSG_CODE_METHOD_CASSINI_SOLDNER=9806;

EPSG_NAME_METHOD_HYPERBOLIC_CASSINI_SOLDNER='Hyperbolic Cassini-Soldner';
EPSG_CODE_METHOD_HYPERBOLIC_CASSINI_SOLDNER=9833;

PROJ_WKT2_NAME_METHOD_EQUIDISTANT_CONIC='Equidistant Conic';

PROJ_WKT2_NAME_METHOD_ECKERT_I='Eckert I';

PROJ_WKT2_NAME_METHOD_ECKERT_II='Eckert II';

PROJ_WKT2_NAME_METHOD_ECKERT_III='Eckert III';

PROJ_WKT2_NAME_METHOD_ECKERT_IV='Eckert IV';

PROJ_WKT2_NAME_METHOD_ECKERT_V='Eckert V';

PROJ_WKT2_NAME_METHOD_ECKERT_VI='Eckert VI';

EPSG_NAME_METHOD_EQUIDISTANT_CYLINDRICAL='Equidistant Cylindrical';
EPSG_CODE_METHOD_EQUIDISTANT_CYLINDRICAL=1028;

EPSG_NAME_METHOD_EQUIDISTANT_CYLINDRICAL_SPHERICAL='Equidistant Cylindrical (Spherical)';
EPSG_CODE_METHOD_EQUIDISTANT_CYLINDRICAL_SPHERICAL=1029;

PROJ_WKT2_NAME_METHOD_FLAT_POLAR_QUARTIC='Flat Polar Quartic';

PROJ_WKT2_NAME_METHOD_GALL_STEREOGRAPHIC='Gall Stereographic';

PROJ_WKT2_NAME_METHOD_GOODE_HOMOLOSINE='Goode Homolosine';

PROJ_WKT2_NAME_METHOD_INTERRUPTED_GOODE_HOMOLOSINE='Interrupted Goode Homolosine';

PROJ_WKT2_NAME_METHOD_INTERRUPTED_GOODE_HOMOLOSINE_OCEAN='Interrupted Goode Homolosine Ocean';

PROJ_WKT2_NAME_METHOD_GEOSTATIONARY_SATELLITE_SWEEP_X='Geostationary Satellite (Sweep X)';

PROJ_WKT2_NAME_METHOD_GEOSTATIONARY_SATELLITE_SWEEP_Y='Geostationary Satellite (Sweep Y)';

PROJ_WKT2_NAME_METHOD_GAUSS_SCHREIBER_TRANSVERSE_MERCATOR='Gauss Schreiber Transverse Mercator';

PROJ_WKT2_NAME_METHOD_GNOMONIC='Gnomonic';

EPSG_NAME_METHOD_HOTINE_OBLIQUE_MERCATOR_VARIANT_A='Hotine Oblique Mercator (variant A)';
EPSG_CODE_METHOD_HOTINE_OBLIQUE_MERCATOR_VARIANT_A=9812;

EPSG_NAME_METHOD_HOTINE_OBLIQUE_MERCATOR_VARIANT_B='Hotine Oblique Mercator (variant B)';
EPSG_CODE_METHOD_HOTINE_OBLIQUE_MERCATOR_VARIANT_B=9815;

PROJ_WKT2_NAME_METHOD_HOTINE_OBLIQUE_MERCATOR_TWO_POINT_NATURAL_ORIGIN='Hotine Oblique Mercator Two Point Natural Origin';

PROJ_WKT2_NAME_INTERNATIONAL_MAP_WORLD_POLYCONIC='International Map of the World Polyconic';

EPSG_NAME_METHOD_KROVAK_NORTH_ORIENTED='Krovak (North Orientated)';
EPSG_CODE_METHOD_KROVAK_NORTH_ORIENTED=1041;

EPSG_NAME_METHOD_KROVAK='Krovak';
EPSG_CODE_METHOD_KROVAK=9819;

EPSG_NAME_METHOD_LAMBERT_AZIMUTHAL_EQUAL_AREA='Lambert Azimuthal Equal Area';
EPSG_CODE_METHOD_LAMBERT_AZIMUTHAL_EQUAL_AREA=9820;

EPSG_NAME_METHOD_LAMBERT_AZIMUTHAL_EQUAL_AREA_SPHERICAL='Lambert Azimuthal Equal Area (Spherical)';
EPSG_CODE_METHOD_LAMBERT_AZIMUTHAL_EQUAL_AREA_SPHERICAL=1027;

PROJ_WKT2_NAME_METHOD_MILLER_CYLINDRICAL='Miller Cylindrical';

EPSG_CODE_METHOD_MERCATOR_VARIANT_A=9804;
EPSG_NAME_METHOD_MERCATOR_VARIANT_A='Mercator (variant A)';

EPSG_CODE_METHOD_MERCATOR_VARIANT_B=9805;
EPSG_NAME_METHOD_MERCATOR_VARIANT_B='Mercator (variant B)';

EPSG_NAME_METHOD_POPULAR_VISUALISATION_PSEUDO_MERCATOR='Popular Visualisation Pseudo Mercator';
EPSG_CODE_METHOD_POPULAR_VISUALISATION_PSEUDO_MERCATOR=1024;

PROJ_WKT2_NAME_METHOD_MOLLWEIDE='Mollweide';

PROJ_WKT2_NAME_METHOD_NATURAL_EARTH='Natural Earth';
PROJ_WKT2_NAME_METHOD_NATURAL_EARTH_II='Natural Earth II';

 EPSG_NAME_METHOD_OBLIQUE_STEREOGRAPHIC='Oblique Stereographic';
EPSG_CODE_METHOD_OBLIQUE_STEREOGRAPHIC=9809;

EPSG_NAME_METHOD_ORTHOGRAPHIC='Orthographic';
EPSG_CODE_METHOD_ORTHOGRAPHIC=9840;

PROJ_WKT2_NAME_ORTHOGRAPHIC_SPHERICAL='Orthographic (Spherical)';

PROJ_WKT2_NAME_METHOD_PATTERSON='Patterson';

EPSG_NAME_METHOD_AMERICAN_POLYCONIC='American Polyconic';
EPSG_CODE_METHOD_AMERICAN_POLYCONIC=9818;

EPSG_NAME_METHOD_POLAR_STEREOGRAPHIC_VARIANT_A='Polar Stereographic (variant A)';
EPSG_CODE_METHOD_POLAR_STEREOGRAPHIC_VARIANT_A=9810;

EPSG_NAME_METHOD_POLAR_STEREOGRAPHIC_VARIANT_B='Polar Stereographic (variant B)';
EPSG_CODE_METHOD_POLAR_STEREOGRAPHIC_VARIANT_B=9829;

PROJ_WKT2_NAME_METHOD_ROBINSON='Robinson';

PROJ_WKT2_NAME_METHOD_SINUSOIDAL='Sinusoidal';

PROJ_WKT2_NAME_METHOD_STEREOGRAPHIC='Stereographic';

PROJ_WKT2_NAME_METHOD_TIMES='Times';

PROJ_WKT2_NAME_METHOD_VAN_DER_GRINTEN='Van Der Grinten';

PROJ_WKT2_NAME_METHOD_WAGNER_I='Wagner I';
PROJ_WKT2_NAME_METHOD_WAGNER_II='Wagner II';
PROJ_WKT2_NAME_METHOD_WAGNER_III='Wagner III';
PROJ_WKT2_NAME_METHOD_WAGNER_IV='Wagner IV';
PROJ_WKT2_NAME_METHOD_WAGNER_V='Wagner V';
PROJ_WKT2_NAME_METHOD_WAGNER_VI='Wagner VI';
PROJ_WKT2_NAME_METHOD_WAGNER_VII='Wagner VII';

PROJ_WKT2_NAME_METHOD_QUADRILATERALIZED_SPHERICAL_CUBE='Quadrilateralized Spherical Cube';

PROJ_WKT2_NAME_METHOD_SPHERICAL_CROSS_TRACK_HEIGHT='Spherical Cross-Track Height';

EPSG_NAME_METHOD_EQUAL_EARTH='Equal Earth';
EPSG_CODE_METHOD_EQUAL_EARTH=1078;

EPSG_NAME_METHOD_LABORDE_OBLIQUE_MERCATOR='Laborde Oblique Mercator';
EPSG_CODE_METHOD_LABORDE_OBLIQUE_MERCATOR=9813;

EPSG_NAME_METHOD_VERTICAL_PERSPECTIVE='Vertical Perspective';
EPSG_CODE_METHOD_VERTICAL_PERSPECTIVE=9838;

PROJ_WKT2_NAME_METHOD_POLE_ROTATION_GRIB_CONVENTION='Pole rotation (GRIB convention)';

EPSG_CODE_METHOD_COLOMBIA_URBAN=1052;
EPSG_NAME_METHOD_COLOMBIA_URBAN='Colombia Urban';

{ ------------------------------------------------------------------------ }

{ Projection parameters }

EPSG_NAME_PARAMETER_COLATITUDE_CONE_AXIS='Co-latitude of cone axis';
EPSG_CODE_PARAMETER_COLATITUDE_CONE_AXIS=1036;

EPSG_NAME_PARAMETER_LATITUDE_OF_NATURAL_ORIGIN='Latitude of natural origin';
EPSG_CODE_PARAMETER_LATITUDE_OF_NATURAL_ORIGIN=8801;

EPSG_NAME_PARAMETER_LONGITUDE_OF_NATURAL_ORIGIN='Longitude of natural origin';
EPSG_CODE_PARAMETER_LONGITUDE_OF_NATURAL_ORIGIN=8802;

EPSG_NAME_PARAMETER_SCALE_FACTOR_AT_NATURAL_ORIGIN='Scale factor at natural origin';
EPSG_CODE_PARAMETER_SCALE_FACTOR_AT_NATURAL_ORIGIN=8805;

EPSG_NAME_PARAMETER_FALSE_EASTING='False easting';
EPSG_CODE_PARAMETER_FALSE_EASTING=8806;

EPSG_NAME_PARAMETER_FALSE_NORTHING='False northing';
EPSG_CODE_PARAMETER_FALSE_NORTHING=8807;

EPSG_NAME_PARAMETER_LATITUDE_PROJECTION_CENTRE='Latitude of projection centre';
EPSG_CODE_PARAMETER_LATITUDE_PROJECTION_CENTRE=8811;

EPSG_NAME_PARAMETER_LONGITUDE_PROJECTION_CENTRE='Longitude of projection centre';
EPSG_CODE_PARAMETER_LONGITUDE_PROJECTION_CENTRE=8812;

EPSG_NAME_PARAMETER_AZIMUTH_INITIAL_LINE='Azimuth of initial line';
EPSG_CODE_PARAMETER_AZIMUTH_INITIAL_LINE=8813;

EPSG_NAME_PARAMETER_ANGLE_RECTIFIED_TO_SKEW_GRID='Angle from Rectified to Skew Grid';
EPSG_CODE_PARAMETER_ANGLE_RECTIFIED_TO_SKEW_GRID=8814;

EPSG_NAME_PARAMETER_SCALE_FACTOR_INITIAL_LINE='Scale factor on initial line';
EPSG_CODE_PARAMETER_SCALE_FACTOR_INITIAL_LINE=8815;

EPSG_NAME_PARAMETER_EASTING_PROJECTION_CENTRE='Easting at projection centre';
EPSG_CODE_PARAMETER_EASTING_PROJECTION_CENTRE=8816;

EPSG_NAME_PARAMETER_NORTHING_PROJECTION_CENTRE='Northing at projection centre';
EPSG_CODE_PARAMETER_NORTHING_PROJECTION_CENTRE=8817;

EPSG_NAME_PARAMETER_LATITUDE_PSEUDO_STANDARD_PARALLEL='Latitude of pseudo standard parallel';
EPSG_CODE_PARAMETER_LATITUDE_PSEUDO_STANDARD_PARALLEL=8818;

EPSG_NAME_PARAMETER_SCALE_FACTOR_PSEUDO_STANDARD_PARALLEL='Scale factor on pseudo standard parallel';
EPSG_CODE_PARAMETER_SCALE_FACTOR_PSEUDO_STANDARD_PARALLEL=8819;

EPSG_NAME_PARAMETER_LATITUDE_FALSE_ORIGIN='Latitude of false origin';
EPSG_CODE_PARAMETER_LATITUDE_FALSE_ORIGIN=8821;

EPSG_NAME_PARAMETER_LONGITUDE_FALSE_ORIGIN='Longitude of false origin';
EPSG_CODE_PARAMETER_LONGITUDE_FALSE_ORIGIN=8822;

EPSG_NAME_PARAMETER_LATITUDE_1ST_STD_PARALLEL='Latitude of 1st standard parallel';
EPSG_CODE_PARAMETER_LATITUDE_1ST_STD_PARALLEL=8823;

EPSG_NAME_PARAMETER_LATITUDE_2ND_STD_PARALLEL='Latitude of 2nd standard parallel';
EPSG_CODE_PARAMETER_LATITUDE_2ND_STD_PARALLEL=8824;

EPSG_NAME_PARAMETER_EASTING_FALSE_ORIGIN='Easting at false origin';
EPSG_CODE_PARAMETER_EASTING_FALSE_ORIGIN=8826;

EPSG_NAME_PARAMETER_NORTHING_FALSE_ORIGIN='Northing at false origin';
EPSG_CODE_PARAMETER_NORTHING_FALSE_ORIGIN=8827;

EPSG_NAME_PARAMETER_LATITUDE_STD_PARALLEL='Latitude of standard parallel';
EPSG_CODE_PARAMETER_LATITUDE_STD_PARALLEL=8832;

EPSG_NAME_PARAMETER_LONGITUDE_OF_ORIGIN='Longitude of origin';
EPSG_CODE_PARAMETER_LONGITUDE_OF_ORIGIN=8833;

EPSG_NAME_PARAMETER_ELLIPSOID_SCALE_FACTOR='Ellipsoid scaling factor';
EPSG_CODE_PARAMETER_ELLIPSOID_SCALE_FACTOR=1038;

EPSG_NAME_PARAMETER_LATITUDE_TOPOGRAPHIC_ORIGIN='Latitude of topocentric origin';
EPSG_CODE_PARAMETER_LATITUDE_TOPOGRAPHIC_ORIGIN=8834;

EPSG_NAME_PARAMETER_LONGITUDE_TOPOGRAPHIC_ORIGIN='Longitude of topocentric origin';
EPSG_CODE_PARAMETER_LONGITUDE_TOPOGRAPHIC_ORIGIN=8835;

EPSG_NAME_PARAMETER_ELLIPSOIDAL_HEIGHT_TOPOCENTRIC_ORIGIN='Ellipsoidal height of topocentric origin';
EPSG_CODE_PARAMETER_ELLIPSOIDAL_HEIGHT_TOPOCENTRIC_ORIGIN=8836;

EPSG_NAME_PARAMETER_VIEWPOINT_HEIGHT='Viewpoint height';
EPSG_CODE_PARAMETER_VIEWPOINT_HEIGHT=8840;

EPSG_NAME_PARAMETER_PROJECTION_PLANE_ORIGIN_HEIGHT='Projection plane origin height';
EPSG_CODE_PARAMETER_PROJECTION_PLANE_ORIGIN_HEIGHT=1039;

{ ------------------------------------------------------------------------ }

{ Other conversions and transformations }

EPSG_NAME_METHOD_COORDINATE_FRAME_GEOCENTRIC='Coordinate Frame rotation (geocentric domain)';
EPSG_CODE_METHOD_COORDINATE_FRAME_GEOCENTRIC=1032;

EPSG_NAME_METHOD_COORDINATE_FRAME_GEOGRAPHIC_2D='Coordinate Frame rotation (geog2D domain)';
EPSG_CODE_METHOD_COORDINATE_FRAME_GEOGRAPHIC_2D=9607;

EPSG_NAME_METHOD_COORDINATE_FRAME_GEOGRAPHIC_3D='Coordinate Frame rotation (geog3D domain)';
EPSG_CODE_METHOD_COORDINATE_FRAME_GEOGRAPHIC_3D=1038;

EPSG_NAME_METHOD_POSITION_VECTOR_GEOCENTRIC='Position Vector transformation (geocentric domain)';
EPSG_CODE_METHOD_POSITION_VECTOR_GEOCENTRIC=1033;

EPSG_NAME_METHOD_POSITION_VECTOR_GEOGRAPHIC_2D='Position Vector transformation (geog2D domain)';
EPSG_CODE_METHOD_POSITION_VECTOR_GEOGRAPHIC_2D=9606;

EPSG_NAME_METHOD_POSITION_VECTOR_GEOGRAPHIC_3D='Position Vector transformation (geog3D domain)';
EPSG_CODE_METHOD_POSITION_VECTOR_GEOGRAPHIC_3D=1037;

EPSG_NAME_METHOD_GEOCENTRIC_TRANSLATION_GEOCENTRIC='Geocentric translations (geocentric domain)';
EPSG_CODE_METHOD_GEOCENTRIC_TRANSLATION_GEOCENTRIC=1031;

EPSG_NAME_METHOD_GEOCENTRIC_TRANSLATION_GEOGRAPHIC_2D='Geocentric translations (geog2D domain)';
EPSG_CODE_METHOD_GEOCENTRIC_TRANSLATION_GEOGRAPHIC_2D=9603;

EPSG_NAME_METHOD_GEOCENTRIC_TRANSLATION_GEOGRAPHIC_3D='Geocentric translations (geog3D domain)';
EPSG_CODE_METHOD_GEOCENTRIC_TRANSLATION_GEOGRAPHIC_3D=1035;

EPSG_NAME_METHOD_TIME_DEPENDENT_POSITION_VECTOR_GEOCENTRIC='Time-dependent Position Vector tfm (geocentric)';
EPSG_CODE_METHOD_TIME_DEPENDENT_POSITION_VECTOR_GEOCENTRIC=1053;

EPSG_NAME_METHOD_TIME_DEPENDENT_POSITION_VECTOR_GEOGRAPHIC_2D='Time-dependent Position Vector tfm (geog2D)';
EPSG_CODE_METHOD_TIME_DEPENDENT_POSITION_VECTOR_GEOGRAPHIC_2D=1054;

EPSG_NAME_METHOD_TIME_DEPENDENT_POSITION_VECTOR_GEOGRAPHIC_3D='Time-dependent Position Vector tfm (geog3D)';
EPSG_CODE_METHOD_TIME_DEPENDENT_POSITION_VECTOR_GEOGRAPHIC_3D=1055;

EPSG_NAME_METHOD_TIME_DEPENDENT_COORDINATE_FRAME_GEOCENTRIC='Time-dependent Coordinate Frame rotation  geocen)';
EPSG_CODE_METHOD_TIME_DEPENDENT_COORDINATE_FRAME_GEOCENTRIC=1056;

EPSG_NAME_METHOD_TIME_DEPENDENT_COORDINATE_FRAME_GEOGRAPHIC_2D='Time-dependent Coordinate Frame rotation (geog2D)';
EPSG_CODE_METHOD_TIME_DEPENDENT_COORDINATE_FRAME_GEOGRAPHIC_2D=1057;

EPSG_NAME_METHOD_TIME_DEPENDENT_COORDINATE_FRAME_GEOGRAPHIC_3D='Time-dependent Coordinate Frame rotation (geog3D)';
EPSG_CODE_METHOD_TIME_DEPENDENT_COORDINATE_FRAME_GEOGRAPHIC_3D=1058;

EPSG_NAME_METHOD_MOLODENSKY_BADEKAS_CF_GEOCENTRIC='Molodensky-Badekas (CF geocentric domain)';
EPSG_CODE_METHOD_MOLODENSKY_BADEKAS_CF_GEOCENTRIC=1034;

EPSG_NAME_METHOD_MOLODENSKY_BADEKAS_PV_GEOCENTRIC='Molodensky-Badekas (PV geocentric domain)';
EPSG_CODE_METHOD_MOLODENSKY_BADEKAS_PV_GEOCENTRIC=1061;

EPSG_NAME_METHOD_MOLODENSKY_BADEKAS_CF_GEOGRAPHIC_3D='Molodensky-Badekas (CF geog3D domain)';
EPSG_CODE_METHOD_MOLODENSKY_BADEKAS_CF_GEOGRAPHIC_3D=1039;

EPSG_NAME_METHOD_MOLODENSKY_BADEKAS_PV_GEOGRAPHIC_3D='Molodensky-Badekas (PV geog3D domain)';
EPSG_CODE_METHOD_MOLODENSKY_BADEKAS_PV_GEOGRAPHIC_3D=1062;

EPSG_NAME_METHOD_MOLODENSKY_BADEKAS_CF_GEOGRAPHIC_2D='Molodensky-Badekas (CF geog2D domain)';
EPSG_CODE_METHOD_MOLODENSKY_BADEKAS_CF_GEOGRAPHIC_2D=9636;

EPSG_NAME_METHOD_MOLODENSKY_BADEKAS_PV_GEOGRAPHIC_2D='Molodensky-Badekas (PV geog2D domain)';
EPSG_CODE_METHOD_MOLODENSKY_BADEKAS_PV_GEOGRAPHIC_2D=1063;

EPSG_CODE_PARAMETER_X_AXIS_TRANSLATION=8605;
EPSG_CODE_PARAMETER_Y_AXIS_TRANSLATION=8606;
EPSG_CODE_PARAMETER_Z_AXIS_TRANSLATION=8607;
EPSG_CODE_PARAMETER_X_AXIS_ROTATION=8608;
EPSG_CODE_PARAMETER_Y_AXIS_ROTATION=8609;
EPSG_CODE_PARAMETER_Z_AXIS_ROTATION=8610;
EPSG_CODE_PARAMETER_SCALE_DIFFERENCE=8611;
EPSG_CODE_PARAMETER_RATE_X_AXIS_TRANSLATION=1040;
EPSG_CODE_PARAMETER_RATE_Y_AXIS_TRANSLATION=1041;
EPSG_CODE_PARAMETER_RATE_Z_AXIS_TRANSLATION=1042;
EPSG_CODE_PARAMETER_RATE_X_AXIS_ROTATION=1043;
EPSG_CODE_PARAMETER_RATE_Y_AXIS_ROTATION=1044;
EPSG_CODE_PARAMETER_RATE_Z_AXIS_ROTATION=1045;
EPSG_CODE_PARAMETER_RATE_SCALE_DIFFERENCE=1046;
EPSG_CODE_PARAMETER_REFERENCE_EPOCH=1047;
EPSG_CODE_PARAMETER_TRANSFORMATION_REFERENCE_EPOCH=1049;

EPSG_NAME_PARAMETER_X_AXIS_TRANSLATION='X-axis translation';
EPSG_NAME_PARAMETER_Y_AXIS_TRANSLATION='Y-axis translation';
EPSG_NAME_PARAMETER_Z_AXIS_TRANSLATION='Z-axis translation';
EPSG_NAME_PARAMETER_X_AXIS_ROTATION='X-axis rotation';
EPSG_NAME_PARAMETER_Y_AXIS_ROTATION='Y-axis rotation';
EPSG_NAME_PARAMETER_Z_AXIS_ROTATION='Z-axis rotation';
EPSG_NAME_PARAMETER_SCALE_DIFFERENCE='Scale difference';

EPSG_NAME_PARAMETER_RATE_X_AXIS_TRANSLATION='Rate of change of X-axis translation';
EPSG_NAME_PARAMETER_RATE_Y_AXIS_TRANSLATION='Rate of change of Y-axis translation';
EPSG_NAME_PARAMETER_RATE_Z_AXIS_TRANSLATION='Rate of change of Z-axis translation';
EPSG_NAME_PARAMETER_RATE_X_AXIS_ROTATION='Rate of change of X-axis rotation';
EPSG_NAME_PARAMETER_RATE_Y_AXIS_ROTATION='Rate of change of Y-axis rotation';
EPSG_NAME_PARAMETER_RATE_Z_AXIS_ROTATION='Rate of change of Z-axis rotation';
EPSG_NAME_PARAMETER_RATE_SCALE_DIFFERENCE='Rate of change of Scale difference';
EPSG_NAME_PARAMETER_REFERENCE_EPOCH='Parameter reference epoch';

EPSG_CODE_PARAMETER_ORDINATE_1_EVAL_POINT=8617;
EPSG_CODE_PARAMETER_ORDINATE_2_EVAL_POINT=8618;
EPSG_CODE_PARAMETER_ORDINATE_3_EVAL_POINT=8667;

EPSG_NAME_PARAMETER_ORDINATE_1_EVAL_POINT='Ordinate 1 of evaluation point';
EPSG_NAME_PARAMETER_ORDINATE_2_EVAL_POINT='Ordinate 2 of evaluation point';
EPSG_NAME_PARAMETER_ORDINATE_3_EVAL_POINT='Ordinate 3 of evaluation point';

EPSG_NAME_PARAMETER_TRANSFORMATION_REFERENCE_EPOCH='Transformation reference epoch';

EPSG_NAME_METHOD_MOLODENSKY='Molodensky';
EPSG_CODE_METHOD_MOLODENSKY=9604;

EPSG_NAME_METHOD_ABRIDGED_MOLODENSKY='Abridged Molodensky';
EPSG_CODE_METHOD_ABRIDGED_MOLODENSKY=9605;

EPSG_CODE_PARAMETER_SEMI_MAJOR_AXIS_DIFFERENCE=8654;
EPSG_CODE_PARAMETER_FLATTENING_DIFFERENCE=8655;

EPSG_NAME_PARAMETER_SEMI_MAJOR_AXIS_DIFFERENCE='Semi-major axis length difference';
EPSG_NAME_PARAMETER_FLATTENING_DIFFERENCE='Flattening difference';

PROJ_WKT2_NAME_PARAMETER_SOUTH_POLE_LATITUDE_GRIB_CONVENTION='Latitude of the southern pole (GRIB convention)';

PROJ_WKT2_NAME_PARAMETER_SOUTH_POLE_LONGITUDE_GRIB_CONVENTION='Longitude of the southern pole (GRIB convention)';

PROJ_WKT2_NAME_PARAMETER_AXIS_ROTATION_GRIB_CONVENTION='Axis rotation (GRIB convention)';

{ ------------------------------------------------------------------------ }

EPSG_CODE_METHOD_NTV1=9614;
EPSG_NAME_METHOD_NTV1='NTv1';

EPSG_CODE_METHOD_NTV2=9615;
EPSG_NAME_METHOD_NTV2='NTv2';

EPSG_CODE_PARAMETER_LATITUDE_LONGITUDE_DIFFERENCE_FILE=8656;
EPSG_NAME_PARAMETER_LATITUDE_LONGITUDE_DIFFERENCE_FILE='Latitude and longitude difference file';

EPSG_NAME_PARAMETER_GEOID_CORRECTION_FILENAME='Geoid (height correction) model file';
EPSG_CODE_PARAMETER_GEOID_CORRECTION_FILENAME=8666;

EPSG_NAME_METHOD_GEOCENTRIC_TRANSLATION_BY_GRID_INTERPOLATION_IGN='Geocentric translation by Grid Interpolation (IGN)';
EPSG_CODE_METHOD_GEOCENTRIC_TRANSLATION_BY_GRID_INTERPOLATION_IGN=1087;

EPSG_CODE_PARAMETER_GEOCENTRIC_TRANSLATION_FILE=8727;
EPSG_NAME_PARAMETER_GEOCENTRIC_TRANSLATION_FILE='Geocentric translation file';

{ ------------------------------------------------------------------------ }

PROJ_WKT2_NAME_METHOD_HEIGHT_TO_GEOG3D='GravityRelatedHeight to Geographic3D';

PROJ_WKT2_NAME_METHOD_CTABLE2='CTABLE2';

PROJ_WKT2_NAME_METHOD_HORIZONTAL_SHIFT_GTIFF='HORIZONTAL_SHIFT_GTIFF';

{ ------------------------------------------------------------------------ }

EPSG_CODE_METHOD_VERTCON=9658;
EPSG_NAME_METHOD_VERTCON_OLDNAME='VERTCON';
EPSG_NAME_METHOD_VERTCON='Vertical Offset by Grid Interpolation (VERTCON)';

EPSG_CODE_METHOD_VERTICALGRID_NZLVD=1071;
EPSG_NAME_METHOD_VERTICALGRID_NZLVD='Vertical Offset by Grid Interpolation (NZLVD)';

EPSG_CODE_METHOD_VERTICALGRID_BEV_AT=1080;
EPSG_NAME_METHOD_VERTICALGRID_BEV_AT='Vertical Offset by Grid Interpolation (BEV AT)';

EPSG_CODE_METHOD_VERTICALGRID_GTX=1084;
EPSG_NAME_METHOD_VERTICALGRID_GTX='Vertical Offset by Grid Interpolation (gtx)';

EPSG_CODE_METHOD_VERTICALGRID_PL_TXT=1101;
EPSG_NAME_METHOD_VERTICALGRID_PL_TXT='Vertical Offset by Grid Interpolation (PL txt)';

EPSG_NAME_PARAMETER_VERTICAL_OFFSET_FILE='Vertical offset file';
EPSG_CODE_PARAMETER_VERTICAL_OFFSET_FILE=8732;

{ ------------------------------------------------------------------------ }

EPSG_CODE_METHOD_NADCON=9613;
EPSG_NAME_METHOD_NADCON='NADCON';

 EPSG_NAME_PARAMETER_LATITUDE_DIFFERENCE_FILE='Latitude difference file';
EPSG_CODE_PARAMETER_LATITUDE_DIFFERENCE_FILE=8657;

EPSG_NAME_PARAMETER_LONGITUDE_DIFFERENCE_FILE='Longitude difference file';
EPSG_CODE_PARAMETER_LONGITUDE_DIFFERENCE_FILE=8658;

{ ------------------------------------------------------------------------ }

EPSG_CODE_METHOD_CHANGE_VERTICAL_UNIT=1069;
EPSG_NAME_METHOD_CHANGE_VERTICAL_UNIT='Change of Vertical Unit';

EPSG_NAME_PARAMETER_UNIT_CONVERSION_SCALAR='Unit conversion scalar';
EPSG_CODE_PARAMETER_UNIT_CONVERSION_SCALAR=1051;

{ ------------------------------------------------------------------------ }

EPSG_CODE_METHOD_LONGITUDE_ROTATION=9601;
EPSG_NAME_METHOD_LONGITUDE_ROTATION='Longitude rotation';

EPSG_CODE_METHOD_VERTICAL_OFFSET=9616;
EPSG_NAME_METHOD_VERTICAL_OFFSET='Vertical Offset';

EPSG_CODE_METHOD_GEOGRAPHIC2D_OFFSETS=9619;
EPSG_NAME_METHOD_GEOGRAPHIC2D_OFFSETS='Geographic2D offsets';

EPSG_CODE_METHOD_GEOGRAPHIC2D_WITH_HEIGHT_OFFSETS=9618;
EPSG_NAME_METHOD_GEOGRAPHIC2D_WITH_HEIGHT_OFFSETS='Geographic2D with Height Offsets';

EPSG_CODE_METHOD_GEOGRAPHIC3D_OFFSETS=9660;
EPSG_NAME_METHOD_GEOGRAPHIC3D_OFFSETS='Geographic3D offsets';

EPSG_CODE_METHOD_GEOGRAPHIC_GEOCENTRIC=9602;

EPSG_NAME_METHOD_GEOGRAPHIC_GEOCENTRIC='Geographic/geocentric conversions';

EPSG_NAME_PARAMETER_LATITUDE_OFFSET='Latitude offset';
EPSG_CODE_PARAMETER_LATITUDE_OFFSET=8601;

EPSG_NAME_PARAMETER_LONGITUDE_OFFSET='Longitude offset';
EPSG_CODE_PARAMETER_LONGITUDE_OFFSET=8602;

EPSG_NAME_PARAMETER_VERTICAL_OFFSET='Vertical Offset';
EPSG_CODE_PARAMETER_VERTICAL_OFFSET=8603;

EPSG_NAME_PARAMETER_GEOID_UNDULATION='Geoid undulation';
EPSG_CODE_PARAMETER_GEOID_UNDULATION=8604;

{ ------------------------------------------------------------------------ }

EPSG_CODE_METHOD_AFFINE_PARAMETRIC_TRANSFORMATION=9624;
EPSG_NAME_METHOD_AFFINE_PARAMETRIC_TRANSFORMATION='Affine parametric transformation';

EPSG_NAME_PARAMETER_A0='A0';
EPSG_CODE_PARAMETER_A0=8623;

EPSG_NAME_PARAMETER_A1='A1';
EPSG_CODE_PARAMETER_A1=8624;

EPSG_NAME_PARAMETER_A2='A2';
EPSG_CODE_PARAMETER_A2=8625;

EPSG_NAME_PARAMETER_B0='B0';
EPSG_CODE_PARAMETER_B0=8639;

EPSG_NAME_PARAMETER_B1='B1';
EPSG_CODE_PARAMETER_B1=8640;

EPSG_NAME_PARAMETER_B2='B2';
EPSG_CODE_PARAMETER_B2=8641;

{ ------------------------------------------------------------------------ }

EPSG_CODE_METHOD_AXIS_ORDER_REVERSAL_2D=9843;
EPSG_NAME_METHOD_AXIS_ORDER_REVERSAL_2D='Axis Order Reversal (2D)';

EPSG_CODE_METHOD_AXIS_ORDER_REVERSAL_3D=9844;
EPSG_NAME_METHOD_AXIS_ORDER_REVERSAL_3D='Axis Order Reversal (Geographic3D horizontal)';

{ ------------------------------------------------------------------------ }

EPSG_CODE_METHOD_HEIGHT_DEPTH_REVERSAL=1068;
EPSG_NAME_METHOD_HEIGHT_DEPTH_REVERSAL='Height Depth Reversal';

{ ------------------------------------------------------------------------ }

EPSG_NAME_METHOD_GEOCENTRIC_TOPOCENTRIC='Geocentric/topocentric conversions';
EPSG_CODE_METHOD_GEOCENTRIC_TOPOCENTRIC=9836;

EPSG_NAME_PARAMETER_GEOCENTRIC_X_TOPOCENTRIC_ORIGIN='Geocentric X of topocentric origin';
EPSG_CODE_PARAMETER_GEOCENTRIC_X_TOPOCENTRIC_ORIGIN=8837;

EPSG_NAME_PARAMETER_GEOCENTRIC_Y_TOPOCENTRIC_ORIGIN='Geocentric Y of topocentric origin';
EPSG_CODE_PARAMETER_GEOCENTRIC_Y_TOPOCENTRIC_ORIGIN=8838;

EPSG_NAME_PARAMETER_GEOCENTRIC_Z_TOPOCENTRIC_ORIGIN='Geocentric Z of topocentric origin';
EPSG_CODE_PARAMETER_GEOCENTRIC_Z_TOPOCENTRIC_ORIGIN=8839;

{ ------------------------------------------------------------------------ }

EPSG_NAME_METHOD_GEOGRAPHIC_TOPOCENTRIC='Geographic/topocentric conversions';
EPSG_CODE_METHOD_GEOGRAPHIC_TOPOCENTRIC=9837;

implementation

end.
